config/routes.rb
Rails.application.routes.draw do
  resources :items

  root 'items#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to items_path, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    if @item.is_complete then
      @item.is_complete = false
    else
      @item.is_complete = true
    end
    redirect_to items_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :description, :is_complete)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<div class="jumbotron">
<%= form_for @item do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <h2 class="small"><%= f.label :title %>:</h2> <%= f.text_field :title, :class => "form-control" %>
  </div><br>
  <div class="form-group">
    <h2 class="small"><%= f.label :description %>:</h2> <%= f.text_area :description, :class => "form-control"  %>
  </div><br>
    <%= f.submit :class => "btn btn-primary" %>
<% end %>
</div>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>
<div class="jumbotron">
  <div class="row well well-lg">
    <div class="col-md-6 col-md-offset-3"><h1>List of items<h1></div>
  </div>
</div>
<div class="col-xs-9">
<script>
  function tableClick(row) {
    if ($("a#row"+row).css("text-decoration") == "none") {
      console.log($("a#row"+row).css("text-decoration"));
      console.log("Found undecorated link!");
      $("a#row"+row).css("text-decoration", "line-through");
    } else { 
      console.log($("a#row"+row).css("text-decoration"));
      console.log("Found decorated link!");
      $("a#row"+row).css("text-decoration", "none");
    }
  }
  function totalClick(){
    $('.show-everything').on('click', function() {
      $('a').attr("display", "inline");
    });
  }
</script>
<table class="table-striped table-responsive center-table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Complete?</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td class="warning"><%= link_to item.title, edit_item_path(item), :id => "row#{item.id}"%></td>
        <td><%= check_box_tag(1, 1, item.is_complete, :onclick=>"tableClick(#{item.id})") %></td>
        <td><%= link_to 'Show', item %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Item', new_item_path %>
</div>

app/views/items/new.html.erb
<h2>New Item</h2>
<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Is complete:</strong>
  <%= @item.is_complete %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Lists</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
  </head>
  <body>
	<div class="container-fluid">
    <div class="row">
        <%= yield %>
	  </div>
	</div>
	<div class="footer">
	  You can contact the author, Hasan Diwan, by <a href="mailto:hasandiwan+lists@gmail.com?subject=lists+feedback">clicking here</a>, by leaving a comment on <a href="http://www.prolificprogrammer.com">his blog</a>, or <a href="http://twitter.com/hdiwan">tweeting @hdiwan</a>.
	</div>
  </body>
</html>